### ISSUE TITLE
Broken Image Links for All Labs

### ISSUE THREAD

**Issue by tumultuous1** [MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals.de-de#1]
# Module: ALL

The images are missing for the German repo.  When should these be expected?

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
All images seem ok now 
Example  https://github.com/MicrosoftLearning/DP-900T00A-Azure-Data-Fundamentals.de-de/blob/OLPRODLOC/Instructions/Labs/dp900-05-stream-lab.md
